# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d1eb05c00f979522ccd0a2cb372806d72c14a200ffa7f45f76883b35343b389701451a36687fa991cf1e9a6b0674f27d51be1afa5fbb2d08165e1fa7da52efe

test:
  secret_key_base: 3c39c086e0e6c8cbbc1f20f30277550f59da208a442f030739580f37e8f64e1903fa347a57339b8627e4747bfa2823b70fb89ebf19211d200482e084559ebfc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
